### ISSUE TITLE
accuracy on test split

### ISSUE THREAD

**Issue by saeideh02** [MILVLG/rosita#11]
Hi, Your article has a great idea, thank you for sharing it, and thank you for your open source code. It's really great and helpful.

I ran the finetuning code with "scripts/train-vqa-vqav2.sh", for "train+trainvalsplit of VQAv2" and I achieved the accuracy successfully.

But after that when I ran the code with "scripts/test-vqa-vqav2.sh" for "evaluation on the test split" it will run ok but doesn't show any result of accuracy as it was in "train-vqa".

Could you please help me with how can I see the result of accuracy for the test split too? I'm a beginner in python and don't know how to do it.

Thanks.

**Comment by MIL-VLG** [comment]
The test results are need to be evaluated on the online server (using the generated prediction json file) rather than on your local environment.
