### ISSUE TITLE
Naming error in the provided vqa2.0 files

### ISSUE THREAD

**Issue by ChCh1999** [MILVLG/rosita#9]
There is a naming error in the provided vqa2.0 [files](https://awma1-my.sharepoint.com/:u:/g/personal/yuz_l0_tn/Ed3QUwvH5SpJkb7lm2bOEXgBqG5OmWExbF0rUq3Es9fmYg?download=1) in  datasets.md.
The file names of the minival2014 files `v2_mscoco_minival2014_annotations.json` and `v2_mscoco_minival2014_questions.json` should be interchanged.

![image](https://user-images.githubusercontent.com/34148951/138819516-8a6b63f7-f21c-47ed-99be-4eadfd23e744.png)
![image](https://user-images.githubusercontent.com/34148951/138819541-664453ad-85fd-40e2-8b1c-be697487a06c.png)

**Comment by MIL-VLG** [comment]
Thanks for pointing out our mistake, we have fixed them and  re-upload the corresponding file :)
